from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lets_go", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=
                """
                CREATE TABLE IF NOT EXISTS public.lets_go_emergencycontact (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL UNIQUE,
                    name VARCHAR(100) NOT NULL,
                    relation VARCHAR(50) NOT NULL,
                    email VARCHAR(254) NOT NULL,
                    phone_no VARCHAR(16) NOT NULL,
                    CONSTRAINT lets_go_emergencycontact_user_id_fk
                        FOREIGN KEY (user_id)
                        REFERENCES public.lets_go_usersdata(id)
                        DEFERRABLE INITIALLY DEFERRED
                );
                """,
            reverse_sql="DROP TABLE IF EXISTS public.lets_go_emergencycontact;",
        ),
    ]
