# Generated by Django 5.2.5 on 2026-01-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0002_create_emergency_contact_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='accountqr_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='cnic_back_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='cnic_front_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='driving_license_back_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='driving_license_front_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='live_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
