# Generated by Django 5.2.5 on 2026-01-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0003_usersdata_accountqr_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdata',
            name='accountqr',
        ),
        migrations.RemoveField(
            model_name='usersdata',
            name='cnic_back_image',
        ),
        migrations.RemoveField(
            model_name='usersdata',
            name='cnic_front_image',
        ),
        migrations.RemoveField(
            model_name='usersdata',
            name='driving_license_back',
        ),
        migrations.RemoveField(
            model_name='usersdata',
            name='driving_license_front',
        ),
        migrations.RemoveField(
            model_name='usersdata',
            name='live_photo',
        ),
        migrations.RemoveField(
            model_name='usersdata',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='documents_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo_back',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo_front',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='documents_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_back_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_front_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
