# Generated by Django 5.2.5 on 2026-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0004_remove_usersdata_accountqr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_geometry',
            field=models.JSONField(blank=True, default=list, help_text='Dense route polyline coordinates for map display (list of {lat, lng} points)'),
        ),
    ]
