# Generated by Django 5.2.5 on 2026-01-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0005_route_route_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pre_ride_reminder_sent',
            field=models.BooleanField(default=False, help_text='Has the T-10 pre-ride reminder been sent for this trip?'),
        ),
    ]
