# Generated by Django 5.2.5 on 2026-01-14 10:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0006_trip_pre_ride_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='started_by_passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_bookings', to='lets_go.usersdata'),
        ),
        migrations.AddField(
            model_name='trip',
            name='live_tracking_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='started_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_trips', to='lets_go.usersdata'),
        ),
        migrations.CreateModel(
            name='PickupCodeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('max_attempts', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('attempts', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=16)),
                ('driver_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('driver_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('passenger_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('passenger_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('verification_result', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_codes', to='lets_go.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_pickup_codes', to='lets_go.usersdata')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_code_verifications', to='lets_go.usersdata')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_codes', to='lets_go.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['booking'], name='lets_go_pic_booking_4dd873_idx'), models.Index(fields=['trip'], name='lets_go_pic_trip_id_09135b_idx'), models.Index(fields=['driver'], name='lets_go_pic_driver__375f9d_idx'), models.Index(fields=['passenger'], name='lets_go_pic_passeng_657018_idx'), models.Index(fields=['status'], name='lets_go_pic_status_c143df_idx')],
            },
        ),
    ]
