# Generated by Django 5.2.5 on 2026-01-15 17:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0008_usernameregistry'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropped_early_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='readiness_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('READY', 'Ready'), ('NOT_READY', 'Not Ready')], default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='ride_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('RIDE_STARTED', 'Ride Started'), ('DROPPED_OFF', 'Dropped Off'), ('DROPPED_EARLY', 'Dropped Early')], default='NOT_STARTED', max_length=20),
        ),
        migrations.CreateModel(
            name='RideAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='lets_go.usersdata')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='lets_go.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='lets_go.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripLiveLocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_location_updates', to='lets_go.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_location_updates', to='lets_go.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_location_updates', to='lets_go.usersdata')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='triplivelocationupdate',
            index=models.Index(fields=['trip', 'recorded_at'], name='lets_go_tri_trip_rec_27ad6a_idx'),
        ),
        migrations.AddIndex(
            model_name='triplivelocationupdate',
            index=models.Index(fields=['user', 'recorded_at'], name='lets_go_tri_user_reco_45a364_idx'),
        ),
        migrations.AddIndex(
            model_name='triplivelocationupdate',
            index=models.Index(fields=['booking', 'recorded_at'], name='lets_go_tri_booking_r_087de4_idx'),
        ),
        migrations.AddIndex(
            model_name='triplivelocationupdate',
            index=models.Index(fields=['role', 'recorded_at'], name='lets_go_tri_role_rec_e2d496_idx'),
        ),
        migrations.AddIndex(
            model_name='rideauditevent',
            index=models.Index(fields=['trip', 'created_at'], name='lets_go_rid_trip_crea_5a4f79_idx'),
        ),
        migrations.AddIndex(
            model_name='rideauditevent',
            index=models.Index(fields=['booking', 'created_at'], name='lets_go_rid_booking__cefdc9_idx'),
        ),
        migrations.AddIndex(
            model_name='rideauditevent',
            index=models.Index(fields=['actor', 'created_at'], name='lets_go_rid_actor_cr_9f7440_idx'),
        ),
        migrations.AddIndex(
            model_name='rideauditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='lets_go_rid_event_ty_82a989_idx'),
        ),
    ]
