# Generated by Django 5.2.5 on 2026-01-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0009_live_tracking_audit_and_booking_ride_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rideauditevent',
            new_name='lets_go_rid_trip_id_2bdc26_idx',
            old_name='lets_go_rid_trip_crea_5a4f79_idx',
        ),
        migrations.RenameIndex(
            model_name='rideauditevent',
            new_name='lets_go_rid_booking_e3b255_idx',
            old_name='lets_go_rid_booking__cefdc9_idx',
        ),
        migrations.RenameIndex(
            model_name='rideauditevent',
            new_name='lets_go_rid_actor_i_0e09d4_idx',
            old_name='lets_go_rid_actor_cr_9f7440_idx',
        ),
        migrations.RenameIndex(
            model_name='rideauditevent',
            new_name='lets_go_rid_event_t_69346d_idx',
            old_name='lets_go_rid_event_ty_82a989_idx',
        ),
        migrations.RenameIndex(
            model_name='triplivelocationupdate',
            new_name='lets_go_tri_trip_id_4718a2_idx',
            old_name='lets_go_tri_trip_rec_27ad6a_idx',
        ),
        migrations.RenameIndex(
            model_name='triplivelocationupdate',
            new_name='lets_go_tri_user_id_626ea1_idx',
            old_name='lets_go_tri_user_reco_45a364_idx',
        ),
        migrations.RenameIndex(
            model_name='triplivelocationupdate',
            new_name='lets_go_tri_booking_ebbd5f_idx',
            old_name='lets_go_tri_booking_r_087de4_idx',
        ),
        migrations.RenameIndex(
            model_name='triplivelocationupdate',
            new_name='lets_go_tri_role_14b21b_idx',
            old_name='lets_go_tri_role_rec_e2d496_idx',
        ),
    ]
