# Generated by Django 5.2.5 on 2026-01-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0011_booking_seats_locked'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='lets_go_boo_seats_l_eb6fea_idx',
            old_name='letsgo_book_seats_l_idx',
        ),
    ]
