# Generated by Django 5.2.5 on 2026-01-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0014_sos_incident'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sosincident',
            new_name='lets_go_sos_status_438bcd_idx',
            old_name='lets_go_sos_status_c_7c9c04_idx',
        ),
        migrations.RenameIndex(
            model_name='sosincident',
            new_name='lets_go_sos_trip_id_dfab27_idx',
            old_name='lets_go_sos_trip_crea_9e0c2f_idx',
        ),
        migrations.RenameIndex(
            model_name='sosincident',
            new_name='lets_go_sos_actor_i_8a0354_idx',
            old_name='lets_go_sos_actor_cr_981f77_idx',
        ),
    ]
