# Generated by Django 5.2.5 on 2026-01-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0019_sos_share_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sossharetoken',
            new_name='lets_go_sos_token_b71096_idx',
            old_name='lets_go_sosshare_token_idx',
        ),
        migrations.RenameIndex(
            model_name='sossharetoken',
            new_name='lets_go_sos_expires_f18a08_idx',
            old_name='lets_go_sosshare_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='sossharetoken',
            new_name='lets_go_sos_revoked_186690_idx',
            old_name='lets_go_sosshare_revoked_idx',
        ),
    ]
