# Generated by Django 5.2.5 on 2026-01-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0021_trip_share_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tripsharetoken',
            new_name='lets_go_tri_token_fb9344_idx',
            old_name='lets_go_trip_token_idx',
        ),
        migrations.RenameIndex(
            model_name='tripsharetoken',
            new_name='lets_go_tri_expires_358d27_idx',
            old_name='lets_go_trip_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='tripsharetoken',
            new_name='lets_go_tri_revoked_a70799_idx',
            old_name='lets_go_trip_revoked_idx',
        ),
    ]
