# Generated by Django 5.2.5 on 2026-01-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0023_vehicle_status_and_change_request'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='changerequest',
            new_name='lets_go_cha_status_626a1d_idx',
            old_name='lets_go_cha_status_c7ef36_idx',
        ),
        migrations.RenameIndex(
            model_name='changerequest',
            new_name='lets_go_cha_entity__2cb434_idx',
            old_name='lets_go_cha_entity_2e2d02_idx',
        ),
        migrations.RenameIndex(
            model_name='changerequest',
            new_name='lets_go_cha_user_id_575bc0_idx',
            old_name='lets_go_cha_user_i_6a0a1e_idx',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
