# Generated by Django 5.2.5 on 2026-01-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0024_rename_lets_go_cha_status_c7ef36_idx_lets_go_cha_status_626a1d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
