# Generated by Django 5.2.5 on 2026-01-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0025_usersdata_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
