# Generated by Django 5.2.5 on 2026-01-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0027_booking_blocked_and_blockeduser'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blockeduser',
            new_name='lets_go_blo_blocker_ef67de_idx',
            old_name='lets_go_blo_blocker_4f5a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='blockeduser',
            new_name='lets_go_blo_blocked_5d41a5_idx',
            old_name='lets_go_blo_blocked__9d0f07_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bargaining_status',
            field=models.CharField(choices=[('NO_NEGOTIATION', 'No Negotiation'), ('PENDING', 'Pending Driver Response'), ('ACCEPTED', 'Accepted by Driver'), ('REJECTED', 'Rejected by Driver'), ('COUNTER_OFFER', 'Driver Counter Offer'), ('BLOCKED', 'Blocked')], default='NO_NEGOTIATION', help_text='Current status of price negotiation', max_length=20),
        ),
    ]
