# Generated by Django 5.2.5 on 2026-01-26 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0028_rename_lets_go_blo_blocker_4f5a1b_idx_lets_go_blo_blocker_ef67de_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_type', models.CharField(choices=[('BOT', 'Bot'), ('ADMIN', 'Admin')], max_length=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to='lets_go.usersdata')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user', 'thread_type'], name='lets_go_sup_user_id_8b9a16_idx'),
                    models.Index(fields=['thread_type', 'last_message_at'], name='lets_go_sup_thread__9e180c_idx'),
                ],
                'unique_together': {('user', 'thread_type')},
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('USER', 'User'), ('BOT', 'Bot'), ('ADMIN', 'Admin')], max_length=10)),
                ('message_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages_sent', to='lets_go.usersdata')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lets_go.supportthread')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['thread', 'created_at'], name='lets_go_sup_thread__9b7b73_idx'),
                ],
            },
        ),
    ]
