# Generated by Django 5.2.5 on 2026-01-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0029_support_chat'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportmessage',
            new_name='lets_go_sup_thread__44f282_idx',
            old_name='lets_go_sup_thread__9b7b73_idx',
        ),
        migrations.RenameIndex(
            model_name='supportthread',
            new_name='lets_go_sup_user_id_259c4d_idx',
            old_name='lets_go_sup_user_id_8b9a16_idx',
        ),
        migrations.RenameIndex(
            model_name='supportthread',
            new_name='lets_go_sup_thread__96c23b_idx',
            old_name='lets_go_sup_thread__9e180c_idx',
        ),
    ]
