# Generated by Django 5.2.5 on 2026-01-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0030_rename_lets_go_sup_thread__9b7b73_idx_lets_go_sup_thread__44f282_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportthread',
            name='admin_last_seen_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='user_last_seen_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
