# Generated by Django 5.2.5 on 2026-01-27 06:40

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0031_support_chat_read_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_number', models.PositiveIntegerField(unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['guest_number'], name='lets_go_gue_guest_n_6acb5a_idx'),
                    models.Index(fields=['username'], name='lets_go_gue_username_0522c8_idx'),
                ],
            },
        ),
        migrations.AlterField(
            model_name='supportthread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to='lets_go.usersdata'),
        ),
        migrations.AddField(
            model_name='supportthread',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to='lets_go.guestuser'),
        ),
        migrations.AlterUniqueTogether(
            name='supportthread',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['guest', 'thread_type'], name='lets_go_sup_guest_t_6b2c3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportthread',
            constraint=models.UniqueConstraint(condition=Q(('user__isnull', False)), fields=('user', 'thread_type'), name='uniq_supportthread_user_thread_type'),
        ),
        migrations.AddConstraint(
            model_name='supportthread',
            constraint=models.UniqueConstraint(condition=Q(('guest__isnull', False)), fields=('guest', 'thread_type'), name='uniq_supportthread_guest_thread_type'),
        ),
        migrations.AddConstraint(
            model_name='supportthread',
            constraint=models.CheckConstraint(check=Q(Q(('user__isnull', False), ('guest__isnull', True)), Q(('user__isnull', True), ('guest__isnull', False)), _connector='OR'), name='chk_supportthread_owner_xor'),
        ),
    ]
