# Generated by Django 5.2.5 on 2026-01-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0032_guest_support_chat'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supportthread',
            name='chk_supportthread_owner_xor',
        ),
        migrations.RenameIndex(
            model_name='guestuser',
            new_name='lets_go_gue_guest_n_0b0a15_idx',
            old_name='lets_go_gue_guest_n_6acb5a_idx',
        ),
        migrations.RenameIndex(
            model_name='guestuser',
            new_name='lets_go_gue_usernam_38fa8c_idx',
            old_name='lets_go_gue_username_0522c8_idx',
        ),
        migrations.RenameIndex(
            model_name='supportthread',
            new_name='lets_go_sup_guest_i_d4270f_idx',
            old_name='lets_go_sup_guest_t_6b2c3a_idx',
        ),
        migrations.AddConstraint(
            model_name='supportthread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest__isnull', True), ('user__isnull', False)), models.Q(('guest__isnull', False), ('user__isnull', True)), _connector='OR'), name='chk_supportthread_owner_xor'),
        ),
    ]
