# Generated by Django 5.2.5 on 2026-01-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_go', '0034_drop_unused_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ride_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('RIDE_STARTED', 'Ride Started'), ('DROPPED_OFF', 'Dropped Off'), ('DROPPED_EARLY', 'Dropped Early'), ('CANCELLED_ON_BOARD', 'Cancelled On Board')], default='NOT_STARTED', max_length=20),
        ),
    ]
